package dev.fbd.datadeletion;

public enum EvaluationStrategy {
    FIRST_REFERENCE_CHECK_THAN_LOCKS_CHECK_THAN_CUSTOM_CHECKS,
    FIRST_LOCKS_CHECK_THAN_REFERENCE_CHECK_THAN_CUSTOM_CHECKS,
    FIRST_CUSTOM_CHECKS_THAN_REFERENCE_CHECK_THAN_LOCKS_CHECK,
    FIRST_CUSTOM_CHECKS_THAN_LOCKS_CHECK_THAN_REFERENCE_CHECK
}
